file.remove("GDP Spread for different continent.png")
file.remove("Median_lifeExp for each continent unordered.png")
file.remove("Pop Avergae for different continent.png")
file.remove("Pop Avergae reordered for different continent.png")
file.remove("Weighted LifeExp by pop vs Year.png")
file.remove("country.tsv")
file.remove("reord_con_life.rds")
file.remove("Median_lifeExp reordered for each continent.png")
file.remove("regression.rds")
file.remove("Asias_worst.rds")
file.remove("Africas_worst.rds")
file.remove("country_plot.png")
file.remove("Rplots.pdf")